### ISSUE TITLE
Trying to run the firebase version of the app as shown in youtube demo, but failed.

### ISSUE THREAD

**Issue by Simon-Li** [davideast/ng2do#18]
David,
Really just trying to use your Youtube version, so I did the copy and change some lines of code here, but failed to run, would you be able to give some hints of what happened. Really appreciated!

---

import {Component, TemplateConfig, bootstrap, Foreach} from 'angular2/angular2';
import {bind} from 'angular2/di';
import {AngularFire, FirebaseArray} from 'firebase/AngularFire';

@Component({
  selector: 'todo-app',
  componentServices: [
    AngularFire, bind(Firebase).toValue(new Firebase('https://webapi.firebaseio-demo.com/test'))
  ],
  template: new TemplateConfig({
    url: 'todo.html',
    directives: [Foreach]
  })
})

class TodoApp {
  todoService: FirebaseArray;
  todoEdit: any;

  constructor(sync: AngularFire) {
    this.todoService = sync.asArray();
    this.todoEdit = null;

---

Believe the rest of the code shall be exactly same as the Github version. Here is the console error logs:

Error during instantiation of Token(AppComponentAnnotatedType)!. ORIGINAL ERROR: TypeError: undefined is not a function

application.js:107 Uncaught (in promise) InstantiationError {keys: Array[3], constructResolvingMessage: function, message: "Error during instantiation of Token(AppComponentAn…NAL ERROR: TypeError: undefined is not a function", addKey: function, toString: function}
VM3745:323 <error>
3308lang.js:64 RangeError: Maximum call stack size exceeded

**Comment by Simon-Li** [comment]
Solved.

**Comment by mkishorem** [comment]
Hi Simon,

How did you solve this problem ? I also ran into the same error after building the Quickstart example from the source. 

Thanks
Kishore

**Comment by ryanstrandt** [comment]
I got the same error. Where has this changed?

**Comment by mkishorem** [comment]
The problem is, in latest version there isn't any Template annotation..change it to view annotation. it should work.

**Comment by Simon-Li** [comment]
@mkishorem @relevantmedia  Suggest to use the Microsoft posted version which works perfectly, otherwise many environmental issues may appear to bother you uncessarily, here is the link:

 http://www.github.com/microsoft/ngconf2015demo
