### ISSUE TITLE
TodoApp broken since quickstart was upgraded to alpha 14

### ISSUE THREAD

**Issue by bouvrais** [davideast/ng2do#19]
Here is the trace:
TypeError: Cannot read property 'annotations' of undefined

TypeError: Cannot read property 'annotations' of undefined
    at ReflectionCapabilities.execute.$__export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflection_capabilities.js:81:40)
    at Reflector.execute.$__export.annotations (http://localhost:3456/quickstart/angular2/src/reflection/reflector.js:81:50)
    at DirectiveMetadataReader.execute.$__export.read (http://localhost:3456/quickstart/angular2/src/core/compiler/directive_metadata_reader.js:31:41)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:127:35
    at Array.map (native)
    at Function.execute.$__export.map (http://localhost:3456/quickstart/angular2/src/facade/collection.js:172:26)
    at Compiler.execute.$__export.createSteps (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:126:43)
    at Compiler.execute.$__export._compileTemplate (http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:164:53)
    at http://localhost:3456/quickstart/angular2/src/core/compiler/compiler.js:154:29
    at Zone.run (http://localhost:3456/quickstart/dist/es6-shim.js:29889:19)
application.js:255 Uncaught (in promise) TypeError: Cannot read property 'annotations' of undefined {stack: (...), message: "Cannot read property 'annotations' of undefined"}

Back syncing "quickstart" just before it was updated to alpha 14 fixes TodoApp.

**Comment by davideast** [comment]
Yes, this version hasn't been fixed for Alpha 14. There are some syntax changes that need to be made.

**Comment by bouvrais** [comment]
I gave it some more time this morning. For the sake of completeness here is the diff of the changes I made to make it work.

```
diff --git a/todo.html b/todo.html
index 9708b47..d0a9df8 100644
--- a/todo.html
+++ b/todo.html
@@ -18,7 +18,7 @@

     <ul id="todo-list">

-      <li *foreach="#todo in todos">
+      <li *for="#todo of todos">

         <div class="view"
             [class.hidden]="todoEdit == todo">
diff --git a/todo.js b/todo.js
index bae2168..9321010 100644
--- a/todo.js
+++ b/todo.js
@@ -1,16 +1,16 @@
-import {Component, Template, bootstrap, Foreach} from 'angular2/angular2';
+import {Component, Template, bootstrap, For} from 'angular2/angular2';
 import {bind} from 'angular2/di';
 import {TodoStore} from 'services/TodoStore';

 @Component({
   selector: 'todo-app',
-  componentServices: [
+  services: [
     TodoStore
   ]
 })
 @Template({
   url: 'todo.html',
-  directives: [Foreach]
+  directives: [For]
 })
 class TodoApp {
   todoStore: TodoStore;
```

**Comment by sivagao** [comment]
@bouvrais it works, why not do a PR for fixing angular 2.0 alpha api changes

**Comment by andreierdoss** [comment]
The changes by @bouvrais fix the issue.

**Comment by bouvrais** [comment]
PR is submitted.

**Comment by tomasnovak6** [comment]
Hello David,

I found your Angular 2 Todo App. I was intrigued by your application, because I am very interested in all about AngularJS 2.0.
However, I would like to ask you what your application should do? After installation and running throught gulp serve I see only label "Loading..." in <todo-app> component. Do I something wrong or where is the problem?

Thank you for your answer.

**Comment by zeeshanjan82** [comment]
I am facing the same issue as @tomasnovak6  please suggest. In the console I get 404 error for : http://localhost:3456/quickstart/dist/es6-shim.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by davideast** [comment]
The es6-shim is no longer needed with the ES5 and TS versions of Angular 2. 

This is a super old version. I'll get it working to the latest soon and freeze the version there.
