### ISSUE TITLE
Tried this out, but I am getting fatal errors...

### ISSUE THREAD

**Issue by richtera** [davideast/ng2do#23]
I know this is Alpha, but I can't really get close enough to even see anything. Should I start elsewhere to check this out?

``` javascript
[Error] SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.
    (anonymous function) (es6-shim.js, line 4941)
[Error] ReferenceError: Can't find variable: System
    global code (localhost, line 14)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
```

**Comment by davideast** [comment]
This repo is in a serious need of an update. However, I'm waiting for some updates before I rewrite it. For now I suggest looking at the [angular.io](https://angular.io) docs. I'll ping you when I get an update for it.
