### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by Yunlong2cn** [davideast/ng2do#25]
![image](https://cloud.githubusercontent.com/assets/1751219/10064687/bf3c6c3c-62ad-11e5-8a01-3bbd23ba398c.png)
![image](https://cloud.githubusercontent.com/assets/1751219/10064689/c410fbce-62ad-11e5-9b56-6b14a53c3787.png)

**Comment by refaelgold** [comment]
I have same problem

**Comment by alfishe** [comment]
+1
