### ISSUE TITLE
Firebase.js and zone.js

### ISSUE THREAD

**Issue by mymai91** [davideast/ng2do#26]
Hi @davideast 
I have just saw "An Angular2 Todo App: First look at App Development in Angular2" on youtube
I have a question: "I don't know why we use firebase.js in this demo?" Beside, I see in structure have `zone.js`. If I don't use `zone.js` It still work, right?
Sorry because I raise issue about video on youtube at here ( I can't comment on youtube )
Thanks

**Comment by sonicoder86** [comment]
`zone.js` is essential for change detection without it wont work.
