### ISSUE TITLE
Example not working anymore

### ISSUE THREAD

**Issue by pitops** [davideast/ng2do#27]
I do not know if this is maintained any more but after running the installation instructions,

it opens a browser tab but stays there,

console looks like this

Uncaught SyntaxError: for-in loop variable declaration may not have an initializer.
localhost/:14 Uncaught ReferenceError: System is not defined
http://localhost:3456/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jazzlevit** [comment]
I've just tried to run this tutorial.
And I had the same error - Uncaught ReferenceError: System is not defined
