### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by nwallace** [davideast/ng2do#4]
I believe I have the Angular2 repo built correctly (the karma tests pass and everything), but this project is not working against it.  I'm on OS X using `http-server` from npm to serve the files, and viewing them with Canary.

As currently written, the installation instructions to symlink the angular build result in a ton of 404s.  I took a loot at [bkad's pending pull request](https://github.com/davideast/ng2do/pull/3) and tried to symlink in the ES5 directory.  That got rid of the 404s, but now I see the following error logged to the console when I try to load the page:

```
Error during instantiation of Token(AppComponentAnnotatedType)!. ORIGINAL ERROR: TypeError: undefined is not a function

-----async gap-----
Error
    at _AsyncInjectorStrategy.execute._AsyncInjectorStrategy.instantiate (http://localhost:8080/ng/angular2/src/di/injector.js:306:17)
    at Injector.execute.$__export._getByKey (http://localhost:8080/ng/angular2/src/di/injector.js:140:33)
    at execute.$__export._resolveDependencies.getDependency (http://localhost:8080/ng/angular2/src/di/injector.js:152:29)
    at Array.map (native)
    at Function.execute.$__export.map (http://localhost:8080/ng/angular2/src/facade/collection.js:166:26)

-----async gap-----
Error
    at _createVmZone (http://localhost:8080/ng/angular2/src/core/application.js:86:16)
    at bootstrap (http://localhost:8080/ng/angular2/src/core/application.js:95:16)
    at y.main (http://localhost:8080/todo.js!eval:13:5)
    at http://localhost:8080/:48:14
```

I presume this error is to blame for the error that actually gets raised:

```
es6-module-loader.src.js:139
    Potentially unhandled rejection [6] Error during instantiation of Token(AppComponentAnnotatedType)! (Token(AppView) -> Token(AppElement) -> Token(AppComponentAnnotatedType)). ORIGINAL ERROR: TypeError: undefined is not a function

    @ es6-module-loader.src.js:139
        (anonymous function)
    @ es6-module-loader.src.js:166
        f
    @ es6-module-loader.src.js:188
        i
    @ zone.js:138
        fnNames.map.forEach.zone.(anonymous function).arguments.(anonymous function)
    @ zone.js:71
        (anonymous function)
    @ zone.js:87
        run
    @ zone.js:64
        zoneBoundFn
```

**Comment by krimple** [comment]
Agreed. I noticed the same thing. Looks like the directories you're pulling from build with a 'lib' directory in them now, and that the fetches for things like Component, TemplateConfig, etc., don't match the locations in the 'from'.

David, I really appreciate the glimpses into the future here. Is it possible to provide a release with a snapshot of Angular as it is at the time, so we can run the whole app without doing a complete build? I know I've been looking for this ever since the video dropped.

**Comment by krimple** [comment]
Note - I was able to find a working version with a snapshot here - https://github.com/gdi2290/angular2do - if it helps anyone reading this.  David, is that the one we should look at?

**Comment by bkad** [comment]
I was able to run with the current HEAD of angular (angular/angular@821f008462abdb24a18d4852bfe3fe04d8695823) by also merging in #5

**Comment by davideast** [comment]
Hey guys,

Building Angular2 from source is not ideal. I'm working on simplifying the process with the npm module for Angular2.

I'm going to go through all of these PRs tonight/tomorrow morning. However, in a day or so the build process will be much easier.

Patrick's demo (based off of this one) builds from source as well. This was the only way before the npm module. Now we can have a stable build that is independent of the constantly changing Angular2 repo. 

You can try out the Angular2 module yourself with `npm install angular2`. This isn't the final packaged version so we're still doing some work on making it an easier setup.

**Comment by krimple** [comment]
Awesome David. Thanks.

**Comment by davideast** [comment]
The latest commit should fix these problems. This app is no longer built from the Angular 2 source, but from the [Angular 2 quickstart](https://github.com/angular/quickstart).
