### ISSUE TITLE
Add the footer routers

### ISSUE THREAD

**Issue by davidhsv** [davideast/ng2do#8]
I revisited the talk and I could not get if the footer [All, Active, Completed] is working or not. I presume that it's not working because the router is not ready yet for angular 2.0 (https://github.com/angular/router)... Am I right?

If so, we need to add the router to this example as soon as possible (or at least make it explicit that is not working by now).

Thanks and congrats for the great work at firebase/angular !

**Comment by davideast** [comment]
Thanks for the kind words, David!

The best way to handle the footer actions [All, Active, Completed] would be to use a Firebase query in addition to the router.

However, right now the Angular2 router is currently in development. You can easily change the query when the link is clicked on, but it is ideal to maintain state in the URL. When the router get's a bit further along we can revisit this.

**Comment by davidhsv** [comment]
Thanks David ! :)

**Comment by davideast** [comment]
Since I do not know when the router will be available, I'm closing this issue. Once it's available I'll open it up again.
